name:                cachix-api
version:             0.1.0.1
github:              "cachix/cachix"
license:             Apache-2.0
author:              "Domen Kožar"
maintainer:          "domen@enlambda.com"
copyright:           "2018 Domen Kožar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Servant HTTP API specification for https://cachix.org

dependencies:
- amazonka
- base >= 4.7 && < 5
- aeson
- bytestring
- base16-bytestring
- cryptonite
- cookie
- conduit >= 1.3.0
- http-media
- http-api-data
- lens
- memory
- servant >= 0.14.1
- servant-auth
- servant-auth-server
- servant-auth-swagger
- servant-streaming
- servant-swagger
- servant-swagger-ui-core
- swagger2
- string-conv
- text
- transformers

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass

ghc-options:
  -Wall
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-name-shadowing
  -fwarn-incomplete-patterns

library:
  source-dirs: src

executables:
  cachix-gen-swagger:
    main:                Main.hs
    source-dirs:         cachix-gen-swagger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix-api
    - aeson

tests:
  cachix-api-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix-api
    - hspec
    - protolude
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
