name:                cachix-api
version:             0.1.0.0
github:              "githubuser/cachix-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cachix-api#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-generic
- text
- bytestring
- lens
- servant-swagger
- servant-swagger-ui
- swagger2
- http-media
- http-api-data

default-extensions:
- OverloadedStrings

ghc-options:
  -Wall
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-name-shadowing
  -fwarn-incomplete-patterns

library:
  source-dirs: src

executables:
  cachix-gen-swagger:
    main:                Main.hs
    source-dirs:         cachix-gen-swagger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix-api
    - aeson

tests:
  cachix-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix-api
