name:                cachix
version:             0.1.0.0
github:              "cachix/cachix"
license:             BSD3
author:              "Domen Kožar"
maintainer:          "domen@enlambda.com"
copyright:           "2018 Domen Kožar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cachix/cachix#readme>

dependencies:
- base >= 4.7 && < 5
- base64-bytestring
- cookie
- ed25519
- servant
- servant-client
- servant-generic
- servant-auth
- servant-auth-client
- directory
- dhall
- here
- http-client
- optparse-applicative
- uri-bytestring
- cachix-api
- text
- versions
- process
- megaparsec
- bytestring
- protolude

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- RecordWildCards

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-name-shadowing
  -fwarn-incomplete-patterns

library:
  source-dirs: src

executables:
  cachix:
    main:                Main.hs
    source-dirs:         cachix
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix

tests:
  cachix-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix
    - hspec
    - protolude
