name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v7
      with:
        name: cachix
        installCommand: nix-env -if .
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: echo " " >> cachix/CHANGELOG.md
    - run: nix-build ci.nix
