name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v5
    - uses: cachix/cachix-action@v2
      with:
        name: cachix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
